name: Deploy webflasher to GitHub Pages

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      version:
        description: 'Version to deploy (e.g. v0.0.2)'
        required: true
        type: string
        default: 'v0.0.1'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Prepare deployment files
        run: |
          echo "Current Files:"
          ls -la
          echo ""
          # Delete old firmware directory in webflasher
          echo "Deleting old firmware dir ..."
          rm -rf webflasher/firmware
          ls -la
          echo ""
          # Create firmware directory in webflasher
          echo "Deleting old firmware dir ..."
          mkdir -p webflasher/firmware
          ls -la
          echo ""
          # Copy the latest binary file
          echo "Copying latest firmwar from main/arduino/button_firmware/binary/ to webflasher/firmware/"
          cp main/arduino/button_firmware/binary/button_firmware.merged.bin webflasher/firmware/
          ls -la webflasher/firmware/
          echo ""
      
      - name: Update version in manifest.json to the last bin release version
        run: |
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${{ inputs.version }}\"/" webflasher/manifest.json
          cat webflasher/manifest.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './webflasher'  # Specifically upload only the webflasher directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3