name: Deploy webflasher to GitHub Pages

on:
  workflow_dispatch:  # Manual trigger for now
  # You could also add auto-trigger on releases later:
  # release:
  #   types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Prepare deployment files
        run: |
          ls -la
          # Delete old firmware directory in webflasher
          rm -rf webflasher/firmware
          ls -la
          # Create firmware directory in webflasher
          mkdir -p webflasher/firmware
          ls -la
          # Copy the latest binary file
          cp main/arduino/button_firmware/binary/button_firmware.merged.bin webflasher/firmware/
          # Verify the file exists
          ls -la webflasher/firmware/
      
      - name: Update version in manifest.json to the correct version
        run: |
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${GITHUB_REF_NAME}\"/" webflasher/manifest.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './webflasher'  # Specifically upload only the webflasher directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3